"""Convert SynthText dataset into TFRecord format, which can be easily integrated into
a TensorFlow pipeline.

NOTICE: **MUST** copy image_shape.pkl into $dataset_dir. image_shape.pkl is generated by 

Usage:
```shell
python tf_convert_syntext.py \
    --dataset_dir=/home/kingease/Downloads/SynthText/ \
    --output_dir=/tmp/ \
    --split_ratio=0.9
```

"""

import tensorflow as tf
from datasets import synthtext_to_tfrecords

synthtext_to_tfrecords.run('/home/mobile/Downloads/SynthText/', '/home/mobile/data/synthtext', shuffling=True)
